import { defineField, defineType } from 'sanity'

export default defineType({
	name: 'popup-settings',
	title: 'Popup Marketing Settings',
	type: 'document',
	groups: [
		{ name: 'general', title: '1. General & Triggers', default: true },
		{ name: 'banner', title: '2. Banner Assets' },
		{ name: 'content', title: '3. Content & Actions' },
	],
	fields: [
		// ================= GROUP 1: GENERAL & TRIGGERS =================
		defineField({
			name: 'isActive',
			title: 'Enable Popup',
			description: 'Toggle popup visibility on the website.',
			type: 'boolean',
			initialValue: false,
			group: 'general',
		}),
		defineField({
			name: 'type',
			title: 'Display Mode',
			description: 'Select the popup display style for your marketing campaign.',
			type: 'string',
			options: {
				list: [
					{
						title: '🎨 Banner Only (Supports Graphic & Transparent Die-Cut Banners)',
						value: 'banner',
					},
					{
						title: '📝 Form with Banner Background (Lead Capture & Voucher Gift)',
						value: 'form',
					},
				],
				layout: 'radio',
			},
			initialValue: 'banner',
			group: 'general',
		}),
		defineField({
			name: 'targetPages',
			title: 'Target Pages',
			description: 'Choose which pages will display this popup.',
			type: 'string',
			options: {
				list: [
					{ title: '🌐 Entire Website (All Pages)', value: 'all' },
					{ title: '🏠 Homepage Only', value: 'home' },
					{ title: '🛍️ Products & Collections Only', value: 'products' },
				],
				layout: 'radio',
			},
			initialValue: 'all',
			group: 'general',
		}),
		defineField({
			name: 'triggerType',
			title: 'Trigger Event',
			description: 'How and when the popup is triggered for visitors.',
			type: 'string',
			options: {
				list: [
					{ title: '⏱️ Time Delay (Show after X seconds)', value: 'delay' },
					{ title: '📜 Scroll Depth (Show when scrolled X%)', value: 'scroll' },
					{ title: '🚪 Exit-Intent (When mouse leaves the page - Desktop)', value: 'exit-intent' },
				],
				layout: 'radio',
			},
			initialValue: 'delay',
			group: 'general',
		}),
		defineField({
			name: 'delaySeconds',
			title: 'Delay Time (Seconds)',
			description: 'Number of seconds to wait before showing the popup (Recommended: 3 - 8s).',
			type: 'number',
			initialValue: 4,
			validation: (Rule) => Rule.min(0).max(120),
			hidden: ({ parent }) => parent?.triggerType !== 'delay',
			group: 'general',
		}),
		defineField({
			name: 'scrollPercentage',
			title: 'Scroll Percentage (%)',
			description: 'Percentage of page scroll depth required to trigger the popup.',
			type: 'number',
			initialValue: 35,
			validation: (Rule) => Rule.min(10).max(90),
			hidden: ({ parent }) => parent?.triggerType !== 'scroll',
			group: 'general',
		}),
		defineField({
			name: 'frequencyDays',
			title: 'Re-display Frequency (Days)',
			description: 'Number of days to hide the popup after the user closes it (0 = show on every session).',
			type: 'number',
			initialValue: 3,
			validation: (Rule) => Rule.min(0).max(90),
			group: 'general',
		}),

		// ================= GROUP 2: BANNER ASSETS =================
		defineField({
			name: 'bannerImage',
			title: 'Desktop Banner Image',
			description: 'Recommended size: 900x600px (3:2) or 800x500px (16:10). Transparent PNG/WebP images are supported. In Form Background mode, ensure the central area provides adequate text contrast. Format: WebP/PNG/JPG < 350KB.',
			type: 'image',
			options: { hotspot: true },
			group: 'banner',
		}),
		defineField({
			name: 'mobileBannerImage',
			title: 'Mobile Banner Image (Optional)',
			description: 'Recommended size: 600x750px (4:5) or 600x600px (1:1). Optimized for mobile screens. Format: WebP/PNG/JPG < 200KB.',
			type: 'image',
			options: { hotspot: true },
			group: 'banner',
		}),
		defineField({
			name: 'transparentBackground',
			title: 'Frameless / Transparent Mode',
			description: 'Removes white card container, border, and box shadow to render transparent PNG/WebP images seamlessly (Recommended for die-cut graphics in Banner Only mode).',
			type: 'boolean',
			initialValue: false,
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),

		// ================= GROUP 3: CONTENT & ACTIONS =================
		// --- Fields for Banner Only Mode ---
		defineField({
			name: 'bannerCtaUrl',
			title: 'Target Link URL',
			description: 'Link destination when visitors click the banner or CTA button (e.g. /collections/all or event URL).',
			placeholder: '/collections/all',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),
		defineField({
			name: 'bannerCtaText',
			title: 'CTA Button Text (Optional)',
			description: 'Leave empty if your banner artwork already contains embedded text or action buttons.',
			placeholder: 'Shop Now / Discover More',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),
		defineField({
			name: 'couponCode',
			title: '1-Click Coupon Code (Optional)',
			description: 'If provided, a 1-click copy coupon button will be displayed on the banner.',
			placeholder: 'SUMMER20',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),
		defineField({
			name: 'bannerBadge',
			title: 'Highlight Badge (Optional)',
			placeholder: 'FLASH SALE / LIMITED OFFER',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),
		defineField({
			name: 'bannerTitle',
			title: 'Banner Heading (Optional)',
			description: 'Used when pairing banner imagery with textual headlines.',
			placeholder: 'Exclusive Member Discounts Up to 40%',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),
		defineField({
			name: 'bannerDescription',
			title: 'Banner Description (Optional)',
			placeholder: 'Apply coupon code at checkout to enjoy special savings on all items.',
			type: 'text',
			rows: 2,
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'content',
		}),

		// --- Fields for Form with Banner Background Mode ---
		defineField({
			name: 'formBadge',
			title: 'Form Badge (Optional)',
			placeholder: 'NEW MEMBER SPECIAL',
			type: 'string',
			initialValue: 'NEW MEMBER SPECIAL',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'formTitle',
			title: 'Form Heading',
			placeholder: 'Get 15% Off Your First Order',
			type: 'string',
			initialValue: 'Get 15% Off Your First Order',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'formDescription',
			title: 'Form Description',
			placeholder: 'Subscribe to our newsletter for exclusive discounts, new releases, and special deals.',
			type: 'text',
			rows: 2,
			initialValue: 'Subscribe to our newsletter for exclusive discounts, new releases, and special deals.',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'formFields',
			title: 'Fields to Collect',
			type: 'string',
			options: {
				list: [
					{ title: '✉️ Email Only (Recommended - Maximum Conversion)', value: 'email' },
					{ title: '📞 Phone Number Only', value: 'phone' },
					{ title: '📋 Both Email & Phone', value: 'both' },
					{ title: '👤 Full (Name + Email + Phone)', value: 'full' },
				],
				layout: 'radio',
			},
			initialValue: 'email',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'formSubmitLabel',
			title: 'Submit Button Label',
			placeholder: 'Claim Voucher Now',
			type: 'string',
			initialValue: 'Claim Voucher Now',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'rewardCouponCode',
			title: 'Reward Voucher Code',
			description: 'Coupon code instantly revealed to the visitor upon successful form submission.',
			placeholder: 'WELCOME15',
			type: 'string',
			initialValue: 'WELCOME15',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'successTitle',
			title: 'Success Heading',
			placeholder: 'Congratulations! Your Voucher is Ready 🎉',
			type: 'string',
			initialValue: 'Congratulations! Your Voucher is Ready 🎉',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
		defineField({
			name: 'successDescription',
			title: 'Success Description',
			placeholder: 'Your exclusive discount code is ready. Copy and apply it during checkout!',
			type: 'text',
			rows: 2,
			initialValue: 'Your exclusive discount code is ready. Copy and apply it during checkout!',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'content',
		}),
	],
	preview: {
		select: {
			isActive: 'isActive',
			type: 'type',
			bannerTitle: 'bannerTitle',
			formTitle: 'formTitle',
		},
		prepare({ isActive, type, bannerTitle, formTitle }) {
			const title = type === 'form' ? formTitle || 'Lead Form with Banner Background' : bannerTitle || 'Marketing Banner'
			return {
				title: title || 'Popup Marketing Settings',
				subtitle: `${isActive ? '🟢 Active' : '⚪ Inactive'} • Mode: ${type === 'form' ? 'Form + Banner Background' : 'Banner Only'}`,
			}
		},
	},
})
