import { defineField, defineType } from 'sanity'

export default defineType({
	name: 'popup-settings',
	title: 'Cấu hình Popup (Popup Settings)',
	type: 'document',
	groups: [
		{ name: 'general', title: '1. Cài đặt chung', default: true },
		{ name: 'trigger', title: '2. Kích hoạt & Tần suất' },
		{ name: 'banner', title: '3. Nội dung Banner' },
		{ name: 'form', title: '4. Nội dung Form Lead' },
		{ name: 'style', title: '5. Giao diện & Hiệu ứng' },
	],
	fields: [
		// ================= GROUP 1: CÀI ĐẶT CHUNG =================
		defineField({
			name: 'isActive',
			title: 'Kích hoạt Popup (Active)',
			description: 'Bật / Tắt hiển thị popup trên website.',
			type: 'boolean',
			initialValue: false,
			group: 'general',
		}),
		defineField({
			name: 'type',
			title: 'Loại Popup (Display Mode)',
			description: 'Chọn dạng hiển thị popup: Banner khuyến mãi hoặc Form thu thập Lead / Newsletter.',
			type: 'string',
			options: {
				list: [
					{ title: '🎨 Dạng Banner Khuyến Mãi (Sale / Promotion Banner)', value: 'banner' },
					{ title: '📝 Dạng Form Thu Thập Lead / Đăng Ký Nhận Voucher (Lead Capture)', value: 'form' },
				],
				layout: 'radio',
			},
			initialValue: 'banner',
			group: 'general',
		}),
		defineField({
			name: 'targetPages',
			title: 'Phạm vi hiển thị (Target Pages)',
			description: 'Chọn trang sẽ xuất hiện popup.',
			type: 'string',
			options: {
				list: [
					{ title: '🌐 Toàn bộ website (All Pages)', value: 'all' },
					{ title: '🏠 Chỉ Trang chủ (Homepage Only)', value: 'home' },
					{ title: '🛍️ Chỉ Trang Sản phẩm & Danh mục (Products & Collections Only)', value: 'products' },
				],
				layout: 'radio',
			},
			initialValue: 'all',
			group: 'general',
		}),

		// ================= GROUP 2: KÍCH HOẠT & TẦN SUẤT =================
		defineField({
			name: 'triggerType',
			title: 'Thời điểm kích hoạt (Trigger Type)',
			description: 'Cách thức kích hoạt popup khi người dùng duyệt web.',
			type: 'string',
			options: {
				list: [
					{ title: '⏱️ Tự động hiện sau X giây (Time Delay)', value: 'delay' },
					{ title: '📜 Hiện khi cuộn trang X% (Scroll Depth)', value: 'scroll' },
					{ title: '🚪 Exit-Intent (Khi rê chuột rời khỏi trang - Desktop)', value: 'exit-intent' },
				],
				layout: 'radio',
			},
			initialValue: 'delay',
			group: 'trigger',
		}),
		defineField({
			name: 'delaySeconds',
			title: 'Thời gian trễ (Giây)',
			description: 'Số giây sau khi tải trang mới hiện popup (Khuyên dùng: 3 - 8s).',
			type: 'number',
			initialValue: 4,
			validation: (Rule) => Rule.min(0).max(120),
			hidden: ({ parent }) => parent?.triggerType !== 'delay',
			group: 'trigger',
		}),
		defineField({
			name: 'scrollPercentage',
			title: 'Phần trăm cuộn trang (%)',
			description: 'Người dùng cuộn xuống bao nhiêu % trang thì kích hoạt popup.',
			type: 'number',
			initialValue: 35,
			validation: (Rule) => Rule.min(10).max(90),
			hidden: ({ parent }) => parent?.triggerType !== 'scroll',
			group: 'trigger',
		}),
		defineField({
			name: 'frequencyDays',
			title: 'Tần suất hiển thị lại sau khi tắt (Ngày)',
			description: 'Nếu khách bấm nút [X] đóng popup, không hiện lại trong bao nhiêu ngày (0 = luôn hiện mỗi lần mở lại trình duyệt).',
			type: 'number',
			initialValue: 3,
			validation: (Rule) => Rule.min(0).max(90),
			group: 'trigger',
		}),

		// ================= GROUP 3: NỘI DUNG BANNER =================
		defineField({
			name: 'bannerImage',
			title: 'Hình ảnh Banner (Desktop)',
			type: 'image',
			options: { hotspot: true },
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'mobileBannerImage',
			title: 'Hình ảnh Banner (Mobile - Tùy chọn)',
			type: 'image',
			options: { hotspot: true },
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'bannerBadge',
			title: 'Badge nổi bật (Nhãn trên cùng)',
			placeholder: 'ƯU ĐÃI ĐỘC QUYỀN / FLASH SALE',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'bannerTitle',
			title: 'Tiêu đề Banner',
			placeholder: 'Đại Tiệc Giảm Giá Đến 40%',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'bannerDescription',
			title: 'Mô tả chi tiết',
			placeholder: 'Nhập mã bên dưới để được giảm ngay 100K cho đơn hàng từ 500K. Áp dụng cho mọi sản phẩm!',
			type: 'text',
			rows: 3,
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'couponCode',
			title: 'Mã Giảm Giá (Coupon Code - Tùy chọn)',
			description: 'Nếu có mã này, popup sẽ hiển thị nút sao chép mã 1-click.',
			placeholder: 'ECOVIP10',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'bannerCtaText',
			title: 'Nút hành động (CTA Button Text)',
			placeholder: 'Khám Phá Ngay / Mua Sắm Ngay',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),
		defineField({
			name: 'bannerCtaUrl',
			title: 'Đường dẫn liên kết (CTA Link)',
			description: 'Link khi bấm vào nút hoặc banner (VD: /collections/all hoặc link ngoài).',
			placeholder: '/collections/all',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'banner',
			group: 'banner',
		}),

		// ================= GROUP 4: NỘI DUNG FORM LEAD =================
		defineField({
			name: 'formImage',
			title: 'Hình ảnh minh họa Form (Tùy chọn)',
			type: 'image',
			options: { hotspot: true },
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formBadge',
			title: 'Badge tiêu đề Form',
			placeholder: 'QUÀ TẶNG THÀNH VIÊN MỚI',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formTitle',
			title: 'Tiêu đề Form',
			placeholder: 'Nhận Ngay Voucher 15% Cho Đơn Đầu Tiên',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formDescription',
			title: 'Mô tả giá trị trao đổi',
			placeholder: 'Đăng ký nhận thông tin để nhận mã giảm giá và các chương trình khuyến mãi độc quyền sớm nhất.',
			type: 'text',
			rows: 2,
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formFields',
			title: 'Trường thông tin cần thu thập',
			type: 'string',
			options: {
				list: [
					{ title: '✉️ Chỉ Email (Khuyên dùng - Tối đa tỷ lệ điền)', value: 'email' },
					{ title: '📞 Chỉ Số điện thoại', value: 'phone' },
					{ title: '📋 Cả Email và Số điện thoại', value: 'both' },
					{ title: '👤 Tên + Email + Số điện thoại', value: 'full' },
				],
				layout: 'radio',
			},
			initialValue: 'email',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formSubmitLabel',
			title: 'Chữ trên nút Gửi (Submit Button Label)',
			placeholder: 'Nhận Mã Ngay',
			type: 'string',
			initialValue: 'Nhận Mã Ngay',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'formPrivacyText',
			title: 'Cam kết bảo mật (Privacy Notice)',
			placeholder: 'Chúng tôi cam kết bảo mật 100% và không spam email của bạn.',
			type: 'string',
			initialValue: 'Chúng tôi cam kết bảo mật 100% và không gửi thư rác.',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'rewardCouponCode',
			title: 'Mã Giảm Giá Tặng Kèm (Reward Voucher Code)',
			description: 'Mã giảm giá hiển thị ngay sau khi khách hàng bấm gửi form thành công.',
			placeholder: 'WELCOME15',
			type: 'string',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'successTitle',
			title: 'Tiêu đề khi gửi thành công',
			placeholder: 'Chúc Mừng Bạn Đã Nhận Mã Thành Công! 🎉',
			type: 'string',
			initialValue: 'Chúc Mừng Bạn Đã Nhận Mã Thành Công! 🎉',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),
		defineField({
			name: 'successDescription',
			title: 'Mô tả khi gửi thành công',
			placeholder: 'Mã giảm giá độc quyền của bạn đã sẵn sàng. Hãy sao chép và áp dụng ngay ở bước thanh toán!',
			type: 'text',
			rows: 2,
			initialValue: 'Mã giảm giá độc quyền của bạn đã sẵn sàng. Hãy sao chép và áp dụng ngay ở bước thanh toán!',
			hidden: ({ parent }) => parent?.type !== 'form',
			group: 'form',
		}),

		// ================= GROUP 5: GIAO DIỆN & HIỆU ỨNG =================
		defineField({
			name: 'layoutStyle',
			title: 'Bố cục Popup (Layout Style)',
			type: 'string',
			options: {
				list: [
					{ title: 'Splitted (Ảnh một bên + Nội dung một bên - Khuyên dùng)', value: 'split' },
					{ title: 'Single Card (Dạng thẻ tập trung ở giữa)', value: 'card' },
					{ title: 'Full Banner Image (Chỉ hiển thị ảnh banner tràn viền)', value: 'full-image' },
				],
			},
			initialValue: 'split',
			group: 'style',
		}),
		defineField({
			name: 'accentColor',
			title: 'Màu nhấn tùy chỉnh (Accent Color - Tùy chọn)',
			description: 'Để trống để tự động lấy theo màu chính của Theme (Primary Color).',
			placeholder: '#059669',
			type: 'string',
			group: 'style',
		}),
	],
	preview: {
		select: {
			isActive: 'isActive',
			type: 'type',
			bannerTitle: 'bannerTitle',
			formTitle: 'formTitle',
		},
		prepare({ isActive, type, bannerTitle, formTitle }) {
			const title = type === 'form' ? formTitle || 'Form Lead Popup' : bannerTitle || 'Banner Popup'
			return {
				title: title || 'Popup Settings',
				subtitle: `${isActive ? '🟢 Đang Bật' : '⚪ Đang Tắt'} • Dạng: ${type === 'form' ? 'Form Lead' : 'Banner'}`,
			}
		},
	},
})
